### ISSUE TITLE
Feature Request: IphoneX

### ISSUE THREAD

**Issue by ChildishDanbino** [m0ngr31/react-native-device-detection#2]
@m0ngr31  - First and foremost we use this package in almost every page on our application so kudos for creating it. I was wondering if the package is still being actively supported? I'd be willing to open a PR for IphoneX now that Apple has that. 

Would be similar to https://github.com/ptelad/react-native-iphone-x-helper but I believe the less packages you can bring in the better. Let me know if you are accepting PRs and I'll open one!

**Comment by m0ngr31** [comment]
Thanks for the kind words. I haven't updated it in a good while, so I'm glad you are getting some mileage out of it. If you want to submit a PR, I'll get it updated on npm.

**Comment by ChildishDanbino** [comment]
@m0ngr31 - PR created https://github.com/m0ngr31/react-native-device-detection/pull/3. Let me know if you have any questions or concerns. Thanks!

**Comment by m0ngr31** [comment]
I just left a comment on your PR.

**Comment by m0ngr31** [comment]
Merged. I'll get this deployed to npm.

**Comment by m0ngr31** [comment]
Updated on npm. Thanks for the PR
